やりたいことリスト詳細画面追加
TechCafeFreedom/Wantum-android pull request #41
Opened 2020-08-14 15:04 UTC by b4tchkn

## TL;DR
やりたいことリストからリスト詳細に遷移できるようにした

- close #31 

## なんでこの変更が必要だった？ (必須)
やりたいことリスト詳細がほしかった

## どんな変更した？ (必須)
- WannadoFragmentを追加
- WannaDoだとモジュール名がwannadoなのにxmlがwanna_doになってわかりにくかったから全体的にrename
- tool_bar.xml作ってリスト詳細画面で使った
- safeArgsでやりたいことリストのタイトルをやりたいことリスト詳細画面に渡してのtool barのタイトルに表示できるようにした

## どうやったらこの変更を確認できる？ (必須)
やりたいことリストのアイテムタップしてみる

## どうやって実装した？

## 苦労したとこ

## 参考にした記事

## Screenshot

Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

## Notes

2020-08-15 13:04 UTC, b4tchkn commented
coreモジュールにある `tool_bar_chel.xml`をresourceモジュールに動かしたら何故か詳細画面いったときにアプリ落ちるから誰か助けてほしす
モジュールの依存関係もちゃんとしてるから参照はできてるけどなんでなんやろ

2020-08-15 14:52 UTC, b4tchkn commented
デザインだとこの画面でBottomNav消し飛ばすみたいだけど本当に消し飛ばす感じでええんかな？
<img src="https://user-images.githubusercontent.com/28699251/90314895-2936f000-df52-11ea-8a10-d53ac4f96c9b.png" width="300" />

2020-08-19 12:30 UTC, Izacchi16 commented
消し飛ばしていいかはれいちぇるさんに聞いてみると良さそう？
コード違和感なかったけどktlintはお済みですか！？

2020-08-24 12:21 UTC, b4tchkn commented on features/resource/src/main/java/com/techcafe/wantum/resource/OnClickToolbarItemListener.kt
> +interface OnClickToolbarItemListener {
signup画面もクリックされたときのリスナーをdatabindingで渡してたからこういうの追加して実装してみたけどどうだい？

2020-08-26 12:24 UTC, Izacchi16 approved these changes, later dismissed
ktlintもかかってるし良さそう！お疲れ様！

2020-08-26 12:24 UTC, Izacchi16 commented on features/resource/src/main/java/com/techcafe/wantum/resource/OnClickToolbarItemListener.kt
> +interface OnClickToolbarItemListener {
ありよりのあり！
好み分かれるだろうけどこれも良さそう！

2020-09-01 04:54 UTC, b4tchkn commented on features/resource/src/main/java/com/techcafe/wantum/resource/OnClickToolbarItemListener.kt
> +interface OnClickToolbarItemListener {
名前 `onToolbarItemClickListener`のほうがかっこいい気がしてきた

2020-09-02 14:34 UTC, felix925 commented on features/resource/build.gradle.kts
> +        dataBinding = true
dataBindingさえtrueにしておけば、viewBindingも使えると思ったのですが、何か意図がある感じですか(?)

2020-09-02 14:34 UTC, felix925 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +class WannadoFragment : Fragment() {
Fragment(R.id.hoge)にして、onViewCreatedでBinding.bind(view)の方がコードが少なくていいかなと思ったのですが、おそらく好みなので修正などはしなくても大丈夫です...！
 (inflateの方がいい理由とかあれば是非教えていただきたく....！)

2020-09-02 14:36 UTC, b4tchkn commented on features/resource/build.gradle.kts
> +        dataBinding = true
おおそれは知らなかったンゴね

2020-09-02 14:36 UTC, b4tchkn commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +class WannadoFragment : Fragment() {
あーここはもともとzooが作ってたとこをただクラス名変えただけなんよね俺笑
そっちの書き方で全部統一しようか？

2020-09-02 14:37 UTC, felix925 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +class WannadoFragment : Fragment() {
なるほど、書き方統一した方が読み手のコストが低くて済むかなと思うので統一する方向が良さそう...！

2020-09-02 14:38 UTC, felix925 commented on features/resource/build.gradle.kts
> +        dataBinding = true
間違ってたらごめンゴ...

2020-09-02 15:01 UTC, Izacchi16 reviewed
approve後に申し訳ない！

2020-09-02 15:01 UTC, Izacchi16 commented on features/resource/build.gradle.kts
> +        dataBinding = true
ふぇり氏のいう通りDaataBindingがViewBindingの機能を内包してるはずだからdataBinding = trueだけで良さそう！
思いっきり見落としていたﾝｺﾞ

2020-09-02 15:01 UTC, Izacchi16 commented on features/resource/src/main/java/com/techcafe/wantum/resource/OnClickToolbarItemListener.kt
> +    fun onShareClick()
個人的好みなんだけどClickイベント系はonClickHogeHoge又はonHogeHogeClickedにするのはどうでしょう！
ちなみにAndroidではonClickHogeHogeが多いイメージ！setOnClickListenerもonClickHogeHogeに則ってる...と思う(あやふやでごめんなさい)

2020-09-02 15:01 UTC, Izacchi16 commented on features/wannado/src/main/res/layout/fragment_wannado_detail.xml
> +            app:layout_constraintTop_toBottomOf="@id/tool_bar_chel_wannado_detail" />
toolbarは1単語で良さそう!

2020-09-03 13:03 UTC, b4tchkn commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +class WannadoFragment : Fragment() {
ちょっとこれ修正仕方わからんかったからふぇりのほうでできる？
`onViewCreated`でBinding.bind(view)すればいいのはわかるんだけど，RecyclerViewとかにアクセスするとき`binding.recyclerView`とかできなくなるなと思って
そこらへん修正して見せてほしい〜

2020-09-04 04:50 UTC, felix925 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +class WannadoFragment : Fragment() {
承知の助侍！

2020-09-04 06:16 UTC, b4tchkn commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoFragment.kt
> +        binding = FragmentWannadoBinding.bind(view)
なるほど！

2020-09-05 05:19 UTC, Izacchi16 approved these changes, later dismissed

2020-09-05 06:58 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +import android.view.ViewGroup
unused 🤔

2020-09-05 06:58 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +import android.view.LayoutInflater
unused 🤔

2020-09-07 10:36 UTC, zoothezoo submitted a review, later dismissed
最高すぎて全米が泣いたんご

2020-09-07 10:42 UTC, Izacchi16 requested changes, later dismissed

2020-09-07 10:42 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +class WannadoDetailFragment : Fragment(R.layout.fragment_wannado_detail), OnClickToolbarItemListener {
これでどうでしょう
```suggestion
class WannadoDetailFragment :
Fragment(R.layout.fragment_wannado_detail),
OnClickToolbarItemListener {
```

2020-09-07 10:48 UTC, Izacchi16 submitted a review, later dismissed
あとは任された！

2020-09-07 10:51 UTC, Izacchi16 approved these changes
LGTM

2020-09-07 10:56 UTC, zoothezoo approved these changes
最高かヒョ

2020-09-07 10:57 UTC, merged