ボトムシートダイアログの表示
TechCafeFreedom/Wantum-android pull request #61
Opened 2020-09-12 13:02 UTC by Izacchi16

## TL;DR

- close #issue-number

## なんでこの変更が必要だった？ (必須)

## どんな変更した？ (必須)

## どうやったらこの変更を確認できる？ (必須)

## Screenshot

Before | After
:--: | :--:
<img src="" width="300" /> | <img src="" width="300" />

## Notes(苦労したとこや参考にした記事など)

2020-09-12 13:04 UTC, ho2ri2s commented
レイアウトのスクショもはっておくれなす！

2020-09-12 13:06 UTC, Izacchi16 commented
TODO 角丸

2020-09-14 16:15 UTC, zoothezoo requested changes

2020-09-14 16:15 UTC, zoothezoo commented on features/wannado/src/main/res/layout/fragment_wannado_edit_dialog.xml
> +</layout>
改行

2020-09-14 16:15 UTC, zoothezoo commented on core/src/main/res/values/strings.xml
>  </resources>
改行

2020-09-14 16:15 UTC, zoothezoo commented on core/src/main/res/drawable/shape_rounded_corners_gray_10dp.xml
> +</selector>
改行

2020-09-14 16:15 UTC, zoothezoo commented on core/src/main/res/drawable/shape_rounded_corners_10dp.xml
> +</selector>
改行

2020-09-14 16:15 UTC, zoothezoo commented on core/src/main/res/drawable/shape_rounded_corner_top.xml
> +</shape>
角丸系のやつって1つの物を使いまわしたりできたりするのかな？
色はまた別でつけるとして

2020-09-14 16:15 UTC, zoothezoo commented on features/wannado/src/main/res/layout/fragment_wannado_edit_dialog.xml
> +        android:background="@drawable/shape_rounded_corner_top"
drawable/shape_rounded_corner_topを@style/AppTheme.ShareDialogにいれていいのでは？

2020-09-16 10:51 UTC, b4tchkn commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +            .show(fragmentManager, "tag")
この `"tag"`って何のために必要なんやろ？
今後色んな場所でこういうの書いたときに他とname space衝突してバグの原因になったりしそうかな？
もうちょっと固有な名前つけたいかも

2020-09-16 10:58 UTC, b4tchkn commented on features/wannado/src/main/res/layout/fragment_wannado_edit_dialog.xml
> +        style="@style/AppTheme.ShareDialog"
全体的に左右にpaddingついてるからそれぞれのViewに設定するより大枠のここで設定したほうがリファクタとかデザイン修正したときの差分が小さいから好きかも

2020-09-16 10:58 UTC, b4tchkn commented on features/wannado/src/main/res/layout/fragment_wannado_edit_dialog.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
外枠をConstraintLayoutにしてここSpaceとかにしてそのSpaceにたいして成約かければネストしないで作れると思ふ

2020-09-16 11:17 UTC, Izacchi16 commented on core/src/main/res/drawable/shape_rounded_corner_top.xml
> +</shape>
styleとして持って色はbackgroundで持たせられそう...?やってみる！

2020-09-16 11:20 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +            .show(fragmentManager, "tag")
fragmentの移動とかの際のbeginTransactionで指定するtagになって被っても問題ないのとNullableなのでNullでも可！

2020-09-16 13:14 UTC, Izacchi16 commented on core/src/main/res/drawable/shape_rounded_corner_top.xml
> +</shape>
保留

2020-09-21 05:32 UTC, Izacchi16 commented on core/build.gradle.kts
> +    implementation(Libs.AndroidX.design)
他のBottomSheetとかにも使うだろうしCoreで！

2020-09-21 05:32 UTC, Izacchi16 commented on core/src/main/res/drawable/ic_baseline_keyboard_arrow_right_24.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
＞のDrawable！

2020-09-21 05:32 UTC, Izacchi16 commented on core/src/main/res/drawable/shape_rounded_corners_10dp.xml
> +<?xml version="1.0" encoding="utf-8"?>
角丸ボタン(クリーム色)

2020-09-21 05:32 UTC, Izacchi16 commented on core/src/main/res/drawable/shape_rounded_corners_gray_10dp.xml
> +<?xml version="1.0" encoding="utf-8"?>
角丸ボタン(灰色)

2020-09-21 05:32 UTC, Izacchi16 commented on core/src/main/res/values/styles.xml
> +    </style>
ここで透明背景になるっぽい

2020-09-21 05:32 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoEditDialogFragment.kt
> +                    resources.getDimension(R.dimen.bottom_sheet_corner_radius)
角丸の設定

2020-09-21 05:33 UTC, Izacchi16 commented
ボタン用のStyle定義必要そう！

2020-09-22 16:42 UTC, b4tchkn commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +            .show(fragmentManager, "tag")
`"tag"`って結局どういう意味だった？

2020-09-22 16:42 UTC, b4tchkn commented on features/wannado/src/main/res/layout/fragment_wannado_edit_dialog.xml
> +            android:textColor="@color/text_light"
このcolorとかsizeとかはtextappearanceでTextStyle当てるだけにしたいね
ほかでも同じサイズと色のテキスト使うとこあると思うし

2020-09-26 10:21 UTC, Izacchi16 commented on features/wannado/src/main/java/com/techcafe/wantum/wannado/WannadoDetailFragment.kt
> +            .show(fragmentManager, "tag")
FragmentTransactinってFragmentの遷移する際に呼ばれるクラス内でtagがあれば被りがあるか見てくれてあればErrorをthrowするくさい...xmlでandroid:tag="unique_tag"みたくやるのと同じっぽい！

2022-07-22 20:32 UTC, closed without merging